.\" Copyright (c) 2010 by John Ashley Burgoyne and the Royal Institute for the 
.\" Advancement of Learning (McGill University). All rights reserved.
.\"
.\" This source is adapted from Suzanne Winsberg's CLASCAL, version 7.01 (May
.\" 1993), written in FORTRAN 77. 
.\" 
.\" Redistribution and use in source and binary forms, with or without 
.\" modification, are permitted provided that the following conditions are met:
.\"
.\"   1. Redistributions of source code must retain the above copyright notice, 
.\"      this list of conditions, and the following disclaimer.
.\"
.\"   2. Redistributions in binary form must reproduce the above copyright
.\"      notice, this list of conditions, and the following disclaimer in the 
.\"      documentation and/or other materials provided with the distribution.
.\"
.\"   3. Neither the name of McGill University nor the names of its contributors
.\"      may be used to endorse or promote products derived from this software 
.\"      without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
.\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
.\" LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd February 28, 2010
.Dt clascalmc 1
.Os
.Sh NAME
.Nm clascalmc
.\" The following lines are read in generating the apropos(man -k) database. Use only key
.\" words here as the database is built based on the words here and in the .ND line. 
.Nd compares nested CLASCAL models using Monte-Carlo tests
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Op Fl g Ar uint
.Op Fl n Ar uint
.Ar exp
.Ar sol0
.Ar sol1
.Sh DESCRIPTION          \" Section Header - required - don't modify
Given CLASCAL solutions
.Ar sol0
and
.Ar sol1
for experiment
.Ar exp
and assuming that the model of
.Ar sol0
is correct,
.Nm
uses a Monte-Carlo method to estimate the probability that fitting the models of
.Ar sol0 
and 
.Ar sol1
to new data would yield a likelihood ratio better than the likelihood
ratio of the given solutions. It then prints its estimated lower bound and upper
bound on this probability to standard output. If this p-value is less than a 
desired alpha (1 minus the confidence level), one can reject the model of
.Ar sol0
in favour of the model of
.Ar sol1 .  
.Pp
For the test to be valid, the models must be nested, i.e., the model of
.Ar sol1
must be a superset of the model of
.Ar sol0 . 
Thus,
.Bl -bullet -offset indent -compact
.It 
the number of dimensions in
.Ar sol1
must be greater than or equal to the number of dimensions in
.Ar sol0 ;
.It 
the number of classes in
.Ar sol1
must be greater than or equal to the number of classes in
.Ar sol0 ;
.It 
if
.Ar sol0 
has shared specificities, then
.Ar sol1 
must have either shared specificities or specificities for each class; and
.It 
if
.Ar sol0
has specificities for each class, then
.Ar sol1
must also have specificities for each class.
.El
.Pp
The options are as follows:
.Bl -tag
.It Fl g Ar uint
Use
.Ar uint
as to seed the random number generator for the Monte-Carlo samples.
.It Fl n Ar uint
Use
.Ar uint
samples to generate the Monte-Carlo estimate. This value must be at least as
large as the reciprocal of the desired alpha 
(e.g., 10 for alpha = 0.1, 20 for alpha = 0.05, 100 for alpha = 0.01, and 1000
for alpha = 0.001); extra iterations increase the precision of the estimate. 
The default value is 20.
.El                      \" Ends the list
.Sh SEE ALSO 
.Xr clascal 1
.Sh AUTHORS
.An John Ashley Burgoyne
.Aq ashley@music.mcgill.ca
